### ISSUE TITLE
Zip code data in db does not have 5 digits

### ISSUE THREAD

**Issue by wolfet410** [datatechcafe/portal#3]
The csv import of the Excel spreadsheet that MetroPCS provided us incorrectly converted the zip codes to numbers. This caused zip codes that begin with a 0nnnn to be converted to nnnn (only 4 digits).

Correct this data in the database, prepending all zip codes with less than 5 digits with 0's so they end up with five digits.

**Comment by aspireddesigns** [comment]
Showing that you can't head leading 0's with numerical fields.
Need to convert the zip's to varchar 5, then pad with 0's
Example:
ALTER TABLE `table` CHANGE `zip` `zip` CHAR(5); #changes type
UPDATE table SET `zip`=LPAD(`zip`, 5, '0'); #pads everything

**Comment by wolfet410** [comment]
Moved to ConnectWise
